---
# base docker-compose configuration
version: '2'
networks:
  default:
    driver: bridge
volumes:
  "jenkins-home":
    external:
      name: infra_jenkins-home

services:
  jenkins:
    privileged: true
    build:
      context: .
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - "jenkins-home:/var/jenkins_home/"
    restart: unless-stopped
